### ISSUE TITLE
Adapt  pulseaudio-modules-nemo and revert lipstick hack 

### ISSUE THREAD

**Issue by rinigus** [nemomobile-ux/main#10]
pulseaudio-modules-nemo has to be ported to new PA. After porting, switch back to `nemo_ng` branch of Lipstick

**Comment by rinigus** [comment]
Build fixed, not sure if it works

**Comment by neochapay** [comment]
Build fine here https://github.com/nemomobile-ux/nemo-packaging/blob/master/pulseaudio-modules-nemo/PKGBUILD
