### ISSUE TITLE
Fedora porting: Qt dependency on GL

### ISSUE THREAD

**Issue by rinigus** [nemomobile-ux/main#11]
In contrast to Sailfish/Nemo, Qt GUI requires libGL:

https://fedora.pkgs.org/32/fedora-updates-x86_64/qt5-qtbase-gui-5.14.2-5.fc32.x86_64.rpm.html

Same for Nemo would be

https://build.merproject.org/package/binary/home:neochapay:mer:release:2020.05:qt/qtbase?arch=aarch64&filename=qt5-qtgui-5.12.7%2Bmaster.20200506062814.1.g41ef5b1-1.1.4.aarch64.rpm&repository=latest_aarch64

As a result, it is impossible to use systems with GLES only - as to compile something requiring Qt GUI with libhybris. 

I wonder whether it means that we will have to repackage Qt as well.

**Comment by neochapay** [comment]
https://build.opensuse.org/project/show/home:neochapay:nemo:qt repo ready

**Comment by rinigus** [comment]
Yees, here we go. 

Some context in addition: https://lists.fedoraproject.org/archives/list/arm@lists.fedoraproject.org/thread/YJXIMCLN76HU65WRSSITMJFZU4IXWPAN/

What is your take, do we need it? Does PinePhone use GLES?

**Comment by neochapay** [comment]
Yes it use GLES

**Comment by rinigus** [comment]
OK, then let's recompile qtbase. Or is there anything else that will be needed? I presume we should take sources from Fedora (https://src.fedoraproject.org/rpms/qt5-qtbase) and then reconfigure them a bit

**Comment by neochapay** [comment]
Use this https://src.fedoraproject.org/rpms/qt5-qtbase/tree/f32

**Comment by rinigus** [comment]
As those don't have sources bundled, I am using http://www.nic.funet.fi/pub/mirrors/fedora.redhat.com/pub/fedora/linux/updates/32/Everything/SRPMS/Packages/q/qt5-qtbase-5.14.2-5.fc32.src.rpm . But it is from Fedora_32 updates

**Comment by rinigus** [comment]
Qt repo is populated and let's see if it builds.

I have made a script and few smaller patches for handling Qt updates. All is pushed to https://github.com/nemomobile-ux/qt5-packaging

It should be simple now to create new patches as well, if needed.

**Comment by neochapay** [comment]
Why only x86(_64) arch ?

**Comment by rinigus** [comment]
Testing currently. As soon as the last packages are ready, I will enable all.

**Comment by rinigus** [comment]
PS: if you need aarch64 ASAP, just enable it. As for ARM32, I would wait as there are very few servers at OBS allocated for it.

**Comment by rinigus** [comment]
It should now build without errors on x86 (32 & 64 bit). I have enabled ARM and pushed all the required patches to https://github.com/nemomobile-ux/qt5-packaging . 

As soon as it is all set, we will be able to use our build of Qt. To avoid constant rebuilding, I suggest to disable building later, when all is ready.

**Comment by rinigus** [comment]
Our repos are constantly rebuilding, which is an issue as Qt was not able to build fully on several arches. So, I have disabled Fedora_32:updates and we are using Fedora_32:standard only. As we are expected to use our own Qt, we stay on 5.14. Currently, we have following chain between projects (inclusion of each other in "Meta"):

buildtools <- qt <- core <- mw <- ux

As Fedora_32:standard does not have i586 (see https://build.opensuse.org/projects/Fedora:32/meta), currently i586 is unresolvable. 

I hope that after full recompile, we will get into more stable situation that should help to work on the packages

**Comment by neochapay** [comment]
We move to manjaro. Closed.
