### ISSUE TITLE
nemo-mobile-session: mixing locations on 64 bit system

### ISSUE THREAD

**Issue by rinigus** [nemomobile-ux/main#12]
nemo-mobile-session is using /usr/lib (while calling scripts), `{_libdir}` in rpm SPEC, and installing unit files using `{_libdir}/systemd`. This all fails on 64-bit system as the locations are not identical.

As it is noarch package, change to use:

- install scripts into /usr/lib - `{_prefix}/lib`
- install unit files using `{_unitdir}` and `{_userunitdir}`

**Comment by neochapay** [comment]
Fixed by https://github.com/nemomobile-ux/nemo-mobile-session/commit/24068b01061066d808fd68cdc6fee6f34e34e2fc
