### ISSUE TITLE
Image building: selection of a tool

### ISSUE THREAD

**Issue by rinigus** [nemomobile-ux/main#13]
We need to select a tool to build images for Nemo. It is due to the current issues with mic (see below).

# Requirements

1. generate images for 
  - aarch64
  - armv7l
  - x86_64

2. support for images with boot sector (virtual box) and without (arm)

3. generate image file with LVM inside:
  - specified volume group name
  - specified partitions: root and home

4. generate image with a filesystem only

5. ability to specify multiple repositories with their priorities

6. support Fedora as a base

7. running customization scripts

8. select packages for installation

9. ability to generate ARM images on x86_64 host

10. good-to-have: support for virtual box images

# Issues with mic

`mic` (https://github.com/mer-tools/mic/tree/jolla) is based on python2 and is using deprecated libzypp bindings (https://github.com/openSUSE/libzypp-bindings). These limitations prevent building libzypp bindings lib (fails in compilation of generated code), problems when using on Fedora 32 (lots of python2 libs were dropped). As Sailfish OS SDK is using older rpm library (or it is compiled with incompatible settings), we cannot generate images on SFOS SDK either. 

# Possible alternatives

Alternatives based from messages in [fedora-arm mailing list](https://lists.fedoraproject.org/archives/list/arm@lists.fedoraproject.org/thread/D7YDXIMFYOWJVLBLYGTAYHKSMRKVZYDR/#QLHWIUNBKILJM6GXRCI4E2WOMWN63FVS) and some searches

* Kiwi https://github.com/OSInside/kiwi
* Lorax https://github.com/weldr/lorax
* OSBuild https://github.com/osbuild/osbuild

**Comment by rinigus** [comment]
# Kiwi

This seems to be workable solution.

- host and image should be the same arch: https://osinside.github.io/kiwi/image_types_and_results.html#architectures

- supports x86_64, arm, aarch64

- is supported by OBS: we can create images at OBS

- supports generation of filesystem image

- supports generation of virtual appliances

- supports generation of tarballs with root packed

- supports generation of LVM, but with postprocessing

- allows to set repo priorities

- allows to customize via scripts at different stages of image building


## LVM

LVM looks to be possible through use of "oem" type. That will generate whole partitioned disk with LVM in use in partition 2. So, would have to mount raw image using loop device, rename logical volume with root (fixed on `LVRoot`) to `root`, and then dump partition 2 to raw image.

**Comment by neochapay** [comment]
We move to manjaro. Closed.
