### ISSUE TITLE
reboot doesn't work

### ISSUE THREAD

**Issue by jmlich** [nemomobile-ux/main#16]
Nemomobile have different privileges model than sailfishos.

The UI triggers reboot via dbus. The pipeline goes to https://github.com/sailfishos/dsme daemon namely https://github.com/sailfishos/dsme/blob/master/dsme/utility.c#L71. The guess is based on following messages in log:

```
$ journalctl -f
Jul 27 14:55:21 manjaro-arm DSME[3747]: Received introspect request: com.nokia.dsme /com/nokia/dsme/request
Jul 27 14:55:22 manjaro-arm DSME[3747]: privileged user not found
```

**Comment by jmlich** [comment]
And now the power button triggers instant reboot, which is also unwanted

**Comment by neochapay** [comment]
https://github.com/sailfishos/dsme/pull/2 i think this may help

**Comment by neochapay** [comment]
fixed with https://github.com/nemomobile-ux/nemo-packaging/commit/d1f013101ed19b48481d1c010acc2fa6919691a0  ?

**Comment by jmlich** [comment]
I want to check it yet.

**Comment by jmlich** [comment]
Yep, this helps. 
After switching of the language is device rebooted automatically.
After clicking on power button is device turned off instantly without "overlay" with power off / reboot options, but this is separate issue.

**Comment by jmlich** [comment]
And thanks for fixing.
