### ISSUE TITLE
"Avahi Zerocon..." icon is created after every reboot

### ISSUE THREAD

**Issue by jmlich** [nemomobile-ux/main#26]
![20211111122826](https://user-images.githubusercontent.com/6171637/141282862-6a306cb2-d60a-4bbf-86ec-0149f18b2fe8.png)

It seems there is a strange behavior of folders. Dropping icon into one folder removes icon from other folder.
https://youtu.be/KV4nfhZ0xLo

**Comment by neochapay** [comment]
Not relevant now?

**Comment by jmlich** [comment]
I haven't seen that for some time
