### ISSUE TITLE
Allow to change Home screen pages bidirectional 

### ISSUE THREAD

**Issue by jmlich** [nemomobile-ux/main#27]
Please allow changing of pages on home screen using both directions. The circular home screen is easier to use. The change was introduced in https://github.com/nemomobile-ux/glacier-home/commit/ee66e029b036ce5a6161303816edbf68883d3ba0

If I understand correctly, there were some issue with PineTab, hence simple revert can break it.

**Comment by neochapay** [comment]
This correct fix ? https://github.com/nemomobile-ux/glacier-home/commit/ca3c725559cbab0a791f064c26dd2cc03525279e

**Comment by jmlich** [comment]
nope, didn't worked correctly. See screenshot in merge request.
