### ISSUE TITLE
Unable to pair headphones as unable to scroll down to find them

### ISSUE THREAD

**Issue by jsarkari01** [nemomobile-ux/main#33]
Tested on PinePhone Pro with ver 1.7.0 and when attempting to pair my bluetooth headphones I can scroll down or more like pull the screen up to see a few more items including my headphones but on lifting finger off the screen I cannot physically scroll down in this setting.

So I tried to drop the display size down to the lowest setting but still couldn't access all the other items so think this scrolling isn't implemented yet or its not working as intended.

**Comment by jsarkari01** [comment]
I found that after rebooting the scaling got smaller than when I set prior to reboot.

But when selecting my headphone they didn't pair.

**Comment by neochapay** [comment]
I think i fix it by https://github.com/nemomobile-ux/glacier-settings/pull/123

**Comment by neochapay** [comment]
fixed nemomobile-ux/glacier-settings#123
