### ISSUE TITLE
connman doesn't work with ui

### ISSUE THREAD

**Issue by jmlich** [nemomobile-ux/main#47]
Lipstick + glacier-settings doesn't work with connman. It seems it is permission issue
The `connmanctl` command shows error when started as manjaro user from command line. It works when started as root.

Following /etc/dbus-1/system.d/connman.conf solves the issue (at least partially)
```
<!DOCTYPE busconfig PUBLIC
        "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
        "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
    <policy group="network">
        <allow own="net.connman"/>
        <allow send_destination="net.connman" send_interface="net.connman.Manager"/>
        <allow send_destination="net.connman" send_interface="net.connman.Agent"/>
        <allow send_destination="net.connman" send_interface="net.connman.Counter"/>
        <allow send_destination="net.connman" send_interface="net.connman.Service"/>
        <allow send_destination="net.connman" send_interface="net.connman.Technology"/>
        <allow send_destination="net.connman" send_interface="org.freedesktop.DBus.Properties"/>
        <allow send_destination="net.connman" send_interface="org.freedesktop.DBus.Introspectable"/>
    </policy>
</busconfig>
```

It is not clear what broke the feature. Other dbus permission could be missing as well.

Possibly related to https://github.com/nemomobile-ux/glacier-wayland-session/pull/5 and https://github.com/nemomobile-ux/main/issues/46

**Comment by neochapay** [comment]
Fixed by https://github.com/nemomobile-ux/glacier-wayland-session/commit/2c869c49f5a116b4236e025d5d68656568d7dc06
