### ISSUE TITLE
Glacier settings doesn't open window

### ISSUE THREAD

**Issue by jmlich** [nemomobile-ux/main#50]
It seems there is some issue with registration of dbus service

```
Jan 19 18:12:30 pinephone glacier-settings[4527]: [] unknown:9 - file:///usr/lib/qt6/qml/Glacier/Controls/Settings/SettingsService.qml:9:5: QML DBusAdaptor: Failed to register service org.nemomobile.qmlsettings
```

The `glacier-settings -p` is running in background, but window is not show upon clicking on desktop icon.

Workaround:
- remove (comment out) DBusAdaptor in /usr/lib/qt6/qml/Glacier/Controls/Settings/SettingsService.qml
- killall glacier-settings and run glacier-settings again

not sure if it is related to https://github.com/nemomobile-ux/libglacierapp/pull/16/files

**Comment by neochapay** [comment]
Fixed into https://github.com/nemomobile-ux/glacier-settings/commit/82d47a42fade07a9d062672c0fa1ed7aeabb00f0 but need to add some interface to enable pressandhold actions
