### ISSUE TITLE
All clicks in Glacier Home are for flipping settings overlay

### ISSUE THREAD

**Issue by rinigus** [nemomobile-ux/main#6]
After the fix of #3, it is possible to see settings overlay in Glacier. However, it is not shown on dragging from the top. Instead, any mouse press is changing the overlay state - it's either opening or closing on a press. No other action is possible, except switching the screens or scrolling through apps. It seems like the area handling settings overlay is processing all events and not propagating it further. Maybe it is behind https://github.com/nemomobile-ux/glacier-home/issues/134

**Comment by rinigus** [comment]
On VBOX, I am getting vbox mouse events as passed with x,y coordinates 0,0 for ScreenGestureArea. That messes up whole handling and leads to opening/closing of controlcenter

Looks like on press, mouse is first reported as 0,0 and, on the next call, with correct coordinates. if I ignore the first call by
```javascript
        if (mouse.x === 0 && mouse.y === 0 ) {
            mouse.accepted = false
            return
        }
```
I can start moving windows around (minimize only though).

also minimization doesn't seem to move window fully out of the window, same with  the gesture from the bottom. 

Still no handling of clicks on app icons (https://github.com/nemomobile-ux/glacier-home/issues/134) nor maximization (https://github.com/nemomobile-ux/glacier-home/issues/133).

**Comment by neochapay** [comment]
Fixed
