### ISSUE TITLE
nemo-qml-plugin-systemsettings disabled SSL certificate info

### ISSUE THREAD

**Issue by rinigus** [nemomobile-ux/main#8]
As Fedora is using newer OpenSSL, access to certificate info has changed. For now, I disabled it in

https://git.sailfishos.org/rinigus/nemo-qml-plugin-systemsettings/commit/03a931d3f3a34c293d90f5c0cb67d8a210c34d06

Thaodan may help to fix it if he gets time. Filing issue here to keep track.

**Comment by rinigus** [comment]
Changes made by Thaodan, but we wait till https://git.sailfishos.org/mer-core/nemo-qml-plugin-systemsettings/merge_requests/154 gets merged.

**Comment by neochapay** [comment]
merged into upstream
